### ISSUE TITLE
How to effectively reload all submodules while working on rhino mac?

### ISSUE THREAD

**Issue by GeneKao** [BlockResearchGroup/compas_rbe#3]
How do I effectively reload all submodules while working on rhino mac?

For example, the change I did with ```compas_rbe.rhino.artists``` does not effect unless I restart rhino or manually reload the submodules as below. 

```python
import imp
# the deeper module has to be reloaded first.
imp.reload(compas_rbe.rhino.artists)
imp.reload(compas_rbe.rhino)

from compas_rbe.rhino import AssemblyArtist
```

**Comment by brgcode** [comment]
gonna close this because nothing we can do about the scriptengine on mac

**Comment by gonzalocasas** [comment]
Did you try the `compas_rhino.unload_modules()` function? It unloads everything with a given string prefix, so `unload_modules('comp') will unload compas and everything related...
