### ISSUE TITLE
Some interface are not detected

### ISSUE THREAD

**Issue by GeneKao** [BlockResearchGroup/compas_rbe#5]
I tried another example like Jenga, and I found some interfaces are not detected. Any idea? 

The Rhino model is in the commit 2be9fe92f339e7b3f43b2e672b3393f8780b3cdf

<img width="1136" alt="screenshot 2018-12-10 at 00 29 34" src="https://user-images.githubusercontent.com/1162842/49704450-8faf2b00-fc13-11e8-85da-f51afa8601fe.png">

**Comment by brgcode** [comment]
is this still relevant?
